# Generated by Django 5.1.1 on 2025-01-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
